kind: Namespace
apiVersion: v1
metadata:
name: opencart
---
apiVersion: v1
kind: Secret
metadata:
  name: oc-$${OCINSTANCE}-externaldb
  namespace: opencart
  labels:
    app.kubernetes.io/name: opencart
    app.kubernetes.io/instance: oc-$${OCINSTANCE}
type: Opaque
data:
  mariadb-password: "$${DBPASSWORD}"
