apiVersion: v1
kind: Secret
metadata:
  name: oc-$${OCINSTANCE}-secret
  namespace: opencart
  labels:
    app.kubernetes.io/name: opencart
    app.kubernetes.io/instance: oc-$${OCINSTANCE}
type: Opaque
data:
  opencart-password: "$${OCPASSWORD}"