apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-$${OCINSTANCE}
  namespace: opencart
  labels:
    app.kubernetes.io/name: opencart
    app.kubernetes.io/instance: oc-$${OCINSTANCE}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opencart
      app.kubernetes.io/instance: oc-$${OCINSTANCE}
  strategy:
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opencart
        app.kubernetes.io/instance: oc-$${OCINSTANCE}
      annotations:
        prometheus.io/port: "9117"
        prometheus.io/scrape: "true"
    spec:
      securityContext:
        fsGroup: 1001
      affinity:
        podAffinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: opencart
                    app.kubernetes.io/instance: oc-$${OCINSTANCE}
                namespaces:
                  - opencart
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "status.localhost"
      initContainers:
      containers:
        - name: oc-$${OCINSTANCE}
          image: docker.io/bitnami/opencart:3.0.3-6-debian-10-r124
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: APACHE_HTTP_PORT_NUMBER
              value: "8080"
            - name: APACHE_HTTPS_PORT_NUMBER
              value: "8443"
            - name: OPENCART_DATABASE_HOST
              value: "$${DBHOST}"
            - name: OPENCART_DATABASE_PORT_NUMBER
              value: "3306"
            - name: OPENCART_DATABASE_NAME
              value: "opencart"
            - name: OPENCART_DATABASE_USER
              value: "$${OCUSER}"
            - name: OPENCART_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oc-$${OCINSTANCE}-externaldb
                  key: mariadb-password
            - name: OPENCART_SKIP_BOOTSTRAP
              value: "yes"
            - name: OPENCART_HOST
              value: "oc-$${OCINSTANCE}.opencart.tkg-cluster-03.cmbu.local"
            - name: OPENCART_USERNAME
              value: "$${OCUSER}"
            - name: OPENCART_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oc-$${OCINSTANCE}-secret
                  key: opencart-password
            - name: OPENCART_EMAIL
              value: "user@example.com"
          envFrom:
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /admin/
              port: http
              httpHeaders:
                - name: Host
                  value: "oc-$${OCINSTANCE}.opencart.tkg-cluster-03.cmbu.local"
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /admin/
              port: http
              httpHeaders:
                - name: Host
                  value: "oc-$${OCINSTANCE}.opencart.tkg-cluster-03.cmbu.local"
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 6
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - name: opencart-data
              mountPath: /bitnami/opencart
              subPath: opencart
            - name: opencart-data
              mountPath: /bitnami/opencart_storage
              subPath: opencart_storage
      volumes:
        - name: opencart-data
          persistentVolumeClaim:
            claimName: oc-$${OCINSTANCE}
