apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oc-smcgeown
  namespace: opencart
  labels:
    app.kubernetes.io/name: opencart
    app.kubernetes.io/instance: oc-smcgeown
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opencart
      app.kubernetes.io/instance: oc-smcgeown
  serviceName: opencart-service
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opencart
        app.kubernetes.io/instance: oc-smcgeown
      annotations:
        prometheus.io/port: "9117"
        prometheus.io/scrape: "true"
    spec:
      securityContext:
        fsGroup: 1001
      affinity:
        podAffinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: opencart
                    app.kubernetes.io/instance: oc-smcgeown
                namespaces:
                  - opencart
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "status.localhost"
      initContainers:
      containers:
        - name: oc-smcgeown
          image: docker.io/bitnami/opencart:3.0.3-6-debian-10-r124
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: APACHE_HTTP_PORT_NUMBER
              value: "8080"
            - name: APACHE_HTTPS_PORT_NUMBER
              value: "8443"
            - name: OPENCART_DATABASE_HOST
              value: "10.176.150.106"
            - name: OPENCART_DATABASE_PORT_NUMBER
              value: "3306"
            - name: OPENCART_DATABASE_NAME
              value: "opencart"
            - name: OPENCART_DATABASE_USER
              value: "ocuser"
            - name: OPENCART_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oc-smcgeown-externaldb
                  key: mariadb-password
            - name: OPENCART_SKIP_BOOTSTRAP
              value: "yes"
            - name: OPENCART_HOST
              value: "oc-smcgeown.opencart.moad.cmbu.local"
            - name: OPENCART_USERNAME
              value: "ocuser"
            - name: OPENCART_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oc-smcgeown-secret
                  key: opencart-password
            - name: OPENCART_EMAIL
              value: "user@example.com"
          envFrom:
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /admin/
              port: http
              httpHeaders:
                - name: Host
                  value: "oc-smcgeown.opencart.tkg-cluster-03.cmbu.local"
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /admin/
              port: http
              httpHeaders:
                - name: Host
                  value: "oc-smcgeown.opencart.tkg-cluster-03.cmbu.local"
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 6
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - name: oc-data
              mountPath: /bitnami/opencart
              subPath: opencart
            - name: oc-data
              mountPath: /bitnami/opencart_storage
              subPath: opencart_storage
            - name: ssl-certs
              mountPath: /opt/bitnami/apache/conf/bitnami/certs
              readOnly: true
      volumes:
        - name: ssl-certs
          secret: 
  volumeClaimTemplates:
  - metadata:
      name: oc-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: vsan-default-storage-policy
      resources:
        requests:
          storage: 2Gi